export enum EnemyType {
  PAINT_BUBBLES = 0,
  HOLLOW_DIAMONDS = 1,
  CRABBY_BOUNCERS = 2,
  MOLECULE_BOUNCERS = 3,
  HOLLOW_CIRCLES = 4,
  SOLID_DIAMONDS = 5,
  BOBBLE_HATS = 6,
  PLANES = 7,
  UP_AND_DOWNERS = 8,
  BONUS_MOLECULE = 9,
  SOLID_DIAMONDS_DEVIANT = 10,
  FUZZ = 11
}
